spring:
  application:
    name: customer-microservice
server:
  port: ${port:9002}
  servlet:
    context-path: /customers

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:9761/eureka

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
        
logging:
  level:
    org.springframework.web:  info
    web: debug
